### ISSUE TITLE
Error AJAX en criticas

### ISSUE THREAD

**Issue by inigovinas** [FILMTALK/final#1]
No se nos recarga con AJAX los comentarios y se recarga toda la página.

**Comment by zmwebdev** [comment]
En criticas.php teneis 'id_pelicula'

``` javascript
    if(isset($_GET['id_pelicula'])){
        $id_pelicula=$_GET['id_pelicula'];           
    }
```

y en valoracion.js 'id'

``` javascript
$('#coment').load('../includes/criticas.php?id='+id);
```

No se si esto soluciona el problema

**Comment by inigovinas** [comment]
Si que estaba mal, pero igualmente seguía recargándose la página. Al final hemos vuelto a probar con event.preventDefault() y funciona!!!
