### ISSUE TITLE
Recargar páginca con PHP

### ISSUE THREAD

**Issue by inigovinas** [FILMTALK/final#2]
Después de realizar el login, queremos que se recargue la página en la que esté situada el usuario, ya que el loggin se realiza desde una ventana modal. Es decir, que haga lo mismo que apretando F5 sin tener que volver a pasarle las variables.

**Comment by zmwebdev** [comment]
Si he entendido bien, por ejemplo si estoy en la página de "Próximamente" y hago el login, que se quede en la misma página.

Una posibilidad sería mandar en el formulario la información desde "donde" se ha hecho el request. Esto se puede hacer metiendo un input hidden en el formulario:

``` html
<input type="hidden" name="paginaactual" value="proximamente">
```

Pero, hacéis esto:

``` php
<?php include("../includes/ventanaModalLogin.html"); ?>
```

y por lo tanto el código es estático ....

Otra posibilidad es guardar en una variable de session esta información: 

``` php
// Redirecciona al perfil del usuario
header("location: /" . $_SESSION['paginaactual']);
```

**Comment by eliAgirre** [comment]
Probaremos con la variable de sesión para poder redirigir. Espero que funcione. :smile:

**Comment by inigovinas** [comment]
Estamos probando con .$_SERVER[HTTP_REFERER], que vuelve a la pagina anterior, 
saludos, 

![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f604.png)

**Comment by inigovinas** [comment]
LO HEMOS CONSEGUIDO!!!!!! AGUUUUUUR!!!!!!
